// extensionsistioio
package extensionsistioio

import (
	_init_ "example.com/cdk8slibrary/imports/extensionsistioio/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"example.com/cdk8slibrary/imports/extensionsistioio/internal"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/cdk8s-team/cdk8s-core-go/cdk8s/v2"
)

type WasmPlugin interface {
	cdk8s.ApiObject
	// The group portion of the API version (e.g. `authorization.k8s.io`).
	ApiGroup() *string
	// The object's API version (e.g. `authorization.k8s.io/v1`).
	ApiVersion() *string
	// The chart in which this object is defined.
	Chart() cdk8s.Chart
	// The object kind.
	Kind() *string
	// Metadata associated with this API object.
	Metadata() cdk8s.ApiObjectMetadataDefinition
	// The name of the API object.
	//
	// If a name is specified in `metadata.name` this will be the name returned.
	// Otherwise, a name will be generated by calling
	// `Chart.of(this).generatedObjectName(this)`, which by default uses the
	// construct path to generate a DNS-compatible name for the resource.
	Name() *string
	// The tree node.
	Node() constructs.Node
	// Create a dependency between this ApiObject and other constructs.
	//
	// These can be other ApiObjects, Charts, or custom.
	AddDependency(dependencies ...constructs.IConstruct)
	// Applies a set of RFC-6902 JSON-Patch operations to the manifest synthesized for this API object.
	//
	// Example:
	//     kubePod.addJsonPatch(JsonPatch.replace('/spec/enableServiceLinks', true));
	//
	AddJsonPatch(ops ...cdk8s.JsonPatch)
	// Renders the object to Kubernetes JSON.
	ToJson() interface{}
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for WasmPlugin
type jsiiProxy_WasmPlugin struct {
	internal.Type__cdk8sApiObject
}

func (j *jsiiProxy_WasmPlugin) ApiGroup() *string {
	var returns *string
	_jsii_.Get(
		j,
		"apiGroup",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WasmPlugin) ApiVersion() *string {
	var returns *string
	_jsii_.Get(
		j,
		"apiVersion",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WasmPlugin) Chart() cdk8s.Chart {
	var returns cdk8s.Chart
	_jsii_.Get(
		j,
		"chart",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WasmPlugin) Kind() *string {
	var returns *string
	_jsii_.Get(
		j,
		"kind",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WasmPlugin) Metadata() cdk8s.ApiObjectMetadataDefinition {
	var returns cdk8s.ApiObjectMetadataDefinition
	_jsii_.Get(
		j,
		"metadata",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WasmPlugin) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WasmPlugin) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}


// Defines a "WasmPlugin" API object.
func NewWasmPlugin(scope constructs.Construct, id *string, props *WasmPluginProps) WasmPlugin {
	_init_.Initialize()

	j := jsiiProxy_WasmPlugin{}

	_jsii_.Create(
		"extensionsistioio.WasmPlugin",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Defines a "WasmPlugin" API object.
func NewWasmPlugin_Override(w WasmPlugin, scope constructs.Construct, id *string, props *WasmPluginProps) {
	_init_.Initialize()

	_jsii_.Create(
		"extensionsistioio.WasmPlugin",
		[]interface{}{scope, id, props},
		w,
	)
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
func WasmPlugin_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	var returns *bool

	_jsii_.StaticInvoke(
		"extensionsistioio.WasmPlugin",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Renders a Kubernetes manifest for "WasmPlugin".
//
// This can be used to inline resource manifests inside other objects (e.g. as templates).
func WasmPlugin_Manifest(props *WasmPluginProps) interface{} {
	_init_.Initialize()

	var returns interface{}

	_jsii_.StaticInvoke(
		"extensionsistioio.WasmPlugin",
		"manifest",
		[]interface{}{props},
		&returns,
	)

	return returns
}

// Returns the `ApiObject` named `Resource` which is a child of the given construct.
//
// If `c` is an `ApiObject`, it is returned directly. Throws an
// exception if the construct does not have a child named `Default` _or_ if
// this child is not an `ApiObject`.
func WasmPlugin_Of(c constructs.IConstruct) cdk8s.ApiObject {
	_init_.Initialize()

	var returns cdk8s.ApiObject

	_jsii_.StaticInvoke(
		"extensionsistioio.WasmPlugin",
		"of",
		[]interface{}{c},
		&returns,
	)

	return returns
}

func WasmPlugin_GVK() *cdk8s.GroupVersionKind {
	_init_.Initialize()
	var returns *cdk8s.GroupVersionKind
	_jsii_.StaticGet(
		"extensionsistioio.WasmPlugin",
		"GVK",
		&returns,
	)
	return returns
}

func (w *jsiiProxy_WasmPlugin) AddDependency(dependencies ...constructs.IConstruct) {
	args := []interface{}{}
	for _, a := range dependencies {
		args = append(args, a)
	}

	_jsii_.InvokeVoid(
		w,
		"addDependency",
		args,
	)
}

func (w *jsiiProxy_WasmPlugin) AddJsonPatch(ops ...cdk8s.JsonPatch) {
	args := []interface{}{}
	for _, a := range ops {
		args = append(args, a)
	}

	_jsii_.InvokeVoid(
		w,
		"addJsonPatch",
		args,
	)
}

func (w *jsiiProxy_WasmPlugin) ToJson() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		w,
		"toJson",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WasmPlugin) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

type WasmPluginProps struct {
	Metadata *cdk8s.ApiObjectMetadata `field:"optional" json:"metadata" yaml:"metadata"`
	// Extend the functionality provided by the Istio proxy through WebAssembly filters.
	//
	// See more details at: https://istio.io/docs/reference/config/proxy_extensions/wasm-plugin.html
	Spec *WasmPluginSpec `field:"optional" json:"spec" yaml:"spec"`
}

// Extend the functionality provided by the Istio proxy through WebAssembly filters.
//
// See more details at: https://istio.io/docs/reference/config/proxy_extensions/wasm-plugin.html
type WasmPluginSpec struct {
	ImagePullPolicy WasmPluginSpecImagePullPolicy `field:"optional" json:"imagePullPolicy" yaml:"imagePullPolicy"`
	// Credentials to use for OCI image pulling.
	ImagePullSecret *string `field:"optional" json:"imagePullSecret" yaml:"imagePullSecret"`
	// Determines where in the filter chain this `WasmPlugin` is to be injected.
	Phase WasmPluginSpecPhase `field:"optional" json:"phase" yaml:"phase"`
	// The configuration that will be passed on to the plugin.
	PluginConfig interface{} `field:"optional" json:"pluginConfig" yaml:"pluginConfig"`
	PluginName *string `field:"optional" json:"pluginName" yaml:"pluginName"`
	// Determines ordering of `WasmPlugins` in the same `phase`.
	Priority *float64 `field:"optional" json:"priority" yaml:"priority"`
	Selector *WasmPluginSpecSelector `field:"optional" json:"selector" yaml:"selector"`
	// SHA256 checksum that will be used to verify Wasm module or OCI container.
	Sha256 *string `field:"optional" json:"sha256" yaml:"sha256"`
	// URL of a Wasm module or OCI container.
	Url *string `field:"optional" json:"url" yaml:"url"`
	VerificationKey *string `field:"optional" json:"verificationKey" yaml:"verificationKey"`
	// Configuration for a Wasm VM.
	VmConfig *WasmPluginSpecVmConfig `field:"optional" json:"vmConfig" yaml:"vmConfig"`
}

type WasmPluginSpecImagePullPolicy string

const (
	// UNSPECIFIED_POLICY.
	WasmPluginSpecImagePullPolicy_UNSPECIFIED_POLICY WasmPluginSpecImagePullPolicy = "UNSPECIFIED_POLICY"
	// IfNotPresent.
	WasmPluginSpecImagePullPolicy_IF_NOT_PRESENT WasmPluginSpecImagePullPolicy = "IF_NOT_PRESENT"
	// Always.
	WasmPluginSpecImagePullPolicy_ALWAYS WasmPluginSpecImagePullPolicy = "ALWAYS"
)

// Determines where in the filter chain this `WasmPlugin` is to be injected.
type WasmPluginSpecPhase string

const (
	// UNSPECIFIED_PHASE.
	WasmPluginSpecPhase_UNSPECIFIED_PHASE WasmPluginSpecPhase = "UNSPECIFIED_PHASE"
	// AUTHN.
	WasmPluginSpecPhase_AUTHN WasmPluginSpecPhase = "AUTHN"
	// AUTHZ.
	WasmPluginSpecPhase_AUTHZ WasmPluginSpecPhase = "AUTHZ"
	// STATS.
	WasmPluginSpecPhase_STATS WasmPluginSpecPhase = "STATS"
)

type WasmPluginSpecSelector struct {
	MatchLabels *map[string]*string `field:"optional" json:"matchLabels" yaml:"matchLabels"`
}

// Configuration for a Wasm VM.
type WasmPluginSpecVmConfig struct {
	// Specifies environment variables to be injected to this VM.
	Env *[]*WasmPluginSpecVmConfigEnv `field:"optional" json:"env" yaml:"env"`
}

type WasmPluginSpecVmConfigEnv struct {
	Name *string `field:"optional" json:"name" yaml:"name"`
	// Value for the environment variable.
	Value *string `field:"optional" json:"value" yaml:"value"`
	ValueFrom WasmPluginSpecVmConfigEnvValueFrom `field:"optional" json:"valueFrom" yaml:"valueFrom"`
}

type WasmPluginSpecVmConfigEnvValueFrom string

const (
	// INLINE.
	WasmPluginSpecVmConfigEnvValueFrom_INLINE WasmPluginSpecVmConfigEnvValueFrom = "INLINE"
	// HOST.
	WasmPluginSpecVmConfigEnvValueFrom_HOST WasmPluginSpecVmConfigEnvValueFrom = "HOST"
)

